name: 发布静态网站

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 获取代码
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.ref_name }}
          
      - name: 准备网站文件
        run: |
          echo "准备静态网站文件"
          
      - name: 发布
        run: |
          echo "网站已准备完毕，等待GitHub Pages服务发布"
          echo "无需额外的下载操作" 