name: 部署五子棋游戏到doooai.com

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 准备部署环境
        run: |
          echo "准备部署环境..."
          
      - name: 获取代码
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          
      - name: 列出文件
        run: |
          echo "网站文件列表:"
          ls -la
          
      - name: 推送到GitHub Pages
        run: |
          echo "五子棋游戏已准备好部署到 https://doooai.com"
          echo "GitHub Pages将自动处理部署过程" 