name: 部署到自定义域名

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://doooai.com
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Pages
        uses: actions/configure-pages@v3
        
      - name: 上传网站文件
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 