name: 部署静态网站

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 直接部署
        run: |
          echo "当前工作目录: $(pwd)"
          echo "列出文件:"
          ls -la
          echo "准备网站文件完成"
          echo "站点内容将直接从仓库发布，无需额外下载" 